version: '3'
services:
  reacty:
    image: node:17-bullseye
    container_name: reacty
    ports:
      - 3000:3000
    user: node
    volumes:
      - reacty-volume:/workspace
      - reacty-vscode-extension-volume:/node/.vscode-server/extensions

volumes:
  reacty-volume:
  reacty-vscode-extension-volume:
